"use client";
import { useEffect, useState } from "react";
import { Crown, Loader2, Play, Radio, Share2, Users, Video } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { buildApiUrl } from "@/lib/api";

export default function PublicChannel(){const {handle}=useParams();const router=useRouter();const [data,setData]=useState<any>();const [tab,setTab]=useState("home");const [joining,setJoining]=useState<string>();useEffect(()=>{fetch(buildApiUrl(`/api/channels/${handle}`)).then(r=>r.ok?r.json():null).then(setData)},[handle]);
 const join=async(tierId:string)=>{const token=localStorage.getItem("accessToken");if(!token){router.push("/login");return}setJoining(tierId);const r=await fetch(buildApiUrl(`/api/channels/tiers/${tierId}/join`),{method:"POST",headers:{Authorization:`Bearer ${token}`}});const d=await r.json();alert(r.ok?"Membership selected. Continue to payment when checkout is connected.":d.error);setJoining(undefined)};
 if(!data)return <div className="min-h-screen bg-[#09090b] grid place-items-center text-white"><Loader2 className="animate-spin text-violet-400"/></div>;const c=data.channel;return <div className="min-h-screen bg-[#09090b] text-white" style={{"--brand":c.primary_color,"--accent":c.accent_color} as any}>
 <div className="h-52 md:h-80 bg-cover bg-center relative" style={{backgroundImage:c.banner_url?`linear-gradient(0deg,#09090b 0%,transparent 60%),url(${c.banner_url})`:`linear-gradient(135deg,${c.primary_color},${c.accent_color})`}}><div className="absolute inset-0 bg-gradient-to-t from-[#09090b] via-transparent to-black/20"/></div>
 <main className="max-w-6xl mx-auto px-5 md:px-8 -mt-16 relative pb-24"><section className="flex flex-col md:flex-row md:items-end gap-5"><div className="w-28 h-28 md:w-36 md:h-36 rounded-[28px] border-[6px] border-[#09090b] overflow-hidden shadow-2xl bg-zinc-900">{c.avatar_url?<img src={c.avatar_url} className="w-full h-full object-cover" alt=""/>:<div className="w-full h-full grid place-items-center text-4xl font-black" style={{background:c.primary_color}}>{c.name[0]}</div>}</div><div className="flex-1 pb-2"><div className="flex items-center gap-2"><h1 className="text-3xl md:text-5xl font-black tracking-tight">{c.name}</h1>{c.owner.is_verified&&<span className="w-5 h-5 rounded-full bg-blue-500 grid place-items-center text-xs">✓</span>}</div><p className="text-zinc-400 mt-1">@{c.handle} · {c.owner.subscriber_count||0} subscribers</p><p className="text-zinc-300 mt-3 max-w-2xl text-sm">{c.description}</p></div><div className="flex gap-2 pb-2"><button onClick={()=>navigator.clipboard.writeText(location.href)} className="p-3 rounded-full border border-white/10"><Share2 className="w-5 h-5"/></button><button className="px-6 py-3 rounded-full font-black text-sm" style={{background:c.primary_color}}>Subscribe</button></div></section>
 <nav className="mt-8 border-b border-white/[.08] flex gap-7 overflow-x-auto">{["home","videos","courses","live","membership"].map(x=><button key={x} onClick={()=>setTab(x)} className={`py-4 capitalize text-sm font-bold border-b-2 ${tab===x?"border-white text-white":"border-transparent text-zinc-500"}`}>{x}</button>)}</nav>
 {(tab==="home"||tab==="live")&&data.live.length>0&&<section className="mt-8"><h2 className="font-black text-xl flex items-center gap-2"><Radio className="text-red-500"/> Live & upcoming</h2><div className="grid md:grid-cols-2 gap-4 mt-4">{data.live.map((l:any)=><button key={l.id} onClick={()=>router.push(`/live/${l.id}`)} className="text-left rounded-3xl overflow-hidden bg-zinc-900 border border-white/[.07]"><div className="aspect-video grid place-items-center relative" style={{background:`linear-gradient(135deg,${c.primary_color}33,${c.accent_color}22)`}}><Radio className="w-12 h-12 opacity-30"/><span className="absolute top-3 left-3 bg-red-500 rounded-lg px-2.5 py-1 text-xs font-black">{l.status.toUpperCase()}</span></div><div className="p-4"><h3 className="font-bold">{l.title}</h3><p className="text-xs text-zinc-500 mt-1">{l.category||"Podcast"}</p></div></button>)}</div></section>}
 {(tab==="home"||tab==="videos")&&<section className="mt-9"><div className="flex justify-between"><h2 className="font-black text-xl flex items-center gap-2"><Video/> Latest videos</h2><span className="text-xs text-zinc-500">{data.videos.length} episodes</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-4">{data.videos.map((v:any)=><button key={v.id} onClick={()=>router.push(`/watch/${v.id}`)} className="text-left group"><div className="aspect-video rounded-2xl overflow-hidden bg-zinc-900 relative">{v.thumbnail&&<img src={v.thumbnail} className="w-full h-full object-cover group-hover:scale-105 transition" alt=""/>}<span className="absolute inset-0 grid place-items-center opacity-0 group-hover:opacity-100 bg-black/40"><Play fill="white"/></span></div><h3 className="font-bold mt-3 line-clamp-2">{v.title}</h3><p className="text-xs text-zinc-500 mt-1">{Number(v.views).toLocaleString()} views</p></button>)}</div></section>}
 {(tab==="home"||tab==="courses")&&data.courses?.length>0&&<section className="mt-9"><div className="flex justify-between"><h2 className="font-black text-xl flex items-center gap-2"><Crown className="text-cyan-400"/> Courses by {c.name}</h2><span className="text-xs text-zinc-500">{data.courses.length} courses</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-4">{data.courses.map((course:any)=><button key={course.id} onClick={()=>router.push(`/course/${course.slug}`)} className="text-left rounded-2xl border border-white/[.08] overflow-hidden group"><div className="aspect-[16/9] bg-gradient-to-br from-cyan-500/20 to-violet-500/20">{course.thumbnail_url&&<img src={course.thumbnail_url} className="w-full h-full object-cover group-hover:scale-105 transition" alt=""/>}</div><div className="p-4"><p className="text-xs uppercase tracking-widest text-cyan-400">{course.category||'Course'}</p><h3 className="font-black mt-1">{course.title}</h3><p className="font-bold mt-3">{course.price_amount?`₹${course.price_amount/100}`:'Free'}</p></div></button>)}</div></section>}
 {tab==="membership"&&<section className="mt-9"><div className="text-center max-w-xl mx-auto"><Crown className="w-10 h-10 text-amber-400 mx-auto"/><h2 className="text-3xl font-black mt-3">Join the inner circle</h2><p className="text-zinc-400 mt-2">Support {c.name} and unlock exclusive member benefits.</p></div><div className="grid md:grid-cols-3 gap-5 mt-8">{c.membership_tiers.map((t:any)=><div key={t.id} className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><Crown className="text-amber-400"/><h3 className="text-xl font-black mt-4">{t.name}</h3><p className="text-3xl font-black mt-2">₹{t.price_amount/100}<span className="text-xs text-zinc-500"> / month</span></p><p className="text-sm text-zinc-400 mt-3">{t.description}</p><ul className="space-y-2 mt-5">{(t.benefits||[]).map((b:string)=><li key={b} className="text-sm flex gap-2"><span style={{color:c.accent_color}}>✓</span>{b}</li>)}</ul><button onClick={()=>join(t.id)} className="w-full mt-6 py-3 rounded-xl font-black text-sm" style={{background:c.primary_color}}>{joining===t.id?<Loader2 className="animate-spin mx-auto"/>:"Join membership"}</button></div>)}</div></section>}
 </main></div>}
