"use client";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, Check, Globe2, Loader2, Lock, Search, ShieldCheck, Trash2, UserPlus } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import DashboardSidebar from "@/components/DashboardSidebar";
import { buildApiUrl } from "@/lib/api";

export default function VideoAccess(){const {id}=useParams();const router=useRouter();const [video,setVideo]=useState<any>();const [grants,setGrants]=useState<any[]>([]);const [handle,setHandle]=useState("");const [expiry,setExpiry]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const auth=()=>({Authorization:`Bearer ${localStorage.getItem("accessToken")}`});
 const load=async()=>{const [v,g]=await Promise.all([fetch(buildApiUrl(`/api/videos/${id}`),{headers:auth()}),fetch(buildApiUrl(`/api/videos/${id}/access`),{headers:auth()})]);if(v.ok)setVideo((await v.json()).video);if(g.ok)setGrants((await g.json()).grants)};useEffect(()=>{load()},[id]);
 const privacy=async(vis:string)=>{setBusy(true);const r=await fetch(buildApiUrl(`/api/videos/${id}`),{method:"PATCH",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({visibility:vis})});if(r.ok)setVideo((await r.json()).video);setBusy(false)};
 const grant=async()=>{if(!handle.trim())return;setBusy(true);setMessage("");const r=await fetch(buildApiUrl(`/api/videos/${id}/access`),{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({handle:handle.replace(/^@/,""),expiresAt:expiry||null})});const d=await r.json();if(r.ok){setHandle("");setExpiry("");setMessage("Viewer approved successfully.");load()}else setMessage(d.error||"Could not approve viewer.");setBusy(false)};
 const revoke=async(userId:string)=>{await fetch(buildApiUrl(`/api/videos/${id}/access/${userId}`),{method:"DELETE",headers:auth()});load()};
 if(!video)return <div className="min-h-screen bg-[#080808] grid place-items-center"><Loader2 className="animate-spin text-violet-400"/></div>;
 return <div className="min-h-screen bg-[#080808] text-white"><DashboardSidebar/><main className="md:ml-60 pb-28"><header className="h-16 px-5 md:px-8 border-b border-white/[.06] flex items-center gap-4"><button onClick={()=>router.back()} className="p-2 rounded-xl hover:bg-white/5"><ArrowLeft/></button><div className="min-w-0"><p className="text-[11px] text-zinc-500 uppercase tracking-widest">Video access</p><h1 className="font-bold truncate">{video.title}</h1></div></header><div className="p-5 md:p-8 max-w-4xl mx-auto space-y-6">
 <section className="glass rounded-3xl p-6"><h2 className="font-bold mb-1">Who can watch?</h2><p className="text-sm text-zinc-500 mb-5">Change visibility anytime. Approved viewers are only used in Private mode.</p><div className="grid sm:grid-cols-2 gap-3"><Choice active={video.visibility==="public"} icon={<Globe2/>} title="Public" text="Everyone on PodLive can watch" onClick={()=>privacy("public")}/><Choice active={video.visibility==="private"} icon={<Lock/>} title="Private" text="Only accounts you approve" onClick={()=>privacy("private")}/></div></section>
 {video.visibility==="private"&&<><section className="rounded-3xl p-6 border border-violet-400/20 bg-violet-500/[.06]"><div className="flex items-center gap-3 mb-5"><div className="p-2.5 rounded-xl bg-violet-500/15"><ShieldCheck className="text-violet-300"/></div><div><h2 className="font-bold">Approve a viewer</h2><p className="text-xs text-zinc-500">They must sign in with this PodLive account</p></div></div>{message&&<p className="text-sm text-violet-200 mb-4">{message}</p>}<div className="grid sm:grid-cols-[1fr_190px_auto] gap-3"><div className="relative"><Search className="absolute left-3 top-3.5 w-4 h-4 text-zinc-500"/><input value={handle} onChange={e=>setHandle(e.target.value)} placeholder="@username" className="input pl-10"/></div><input type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)} className="input text-zinc-300"/><button onClick={grant} disabled={busy||!handle} className="bg-violet-500 hover:bg-violet-400 disabled:opacity-50 px-5 rounded-xl font-bold text-sm flex items-center justify-center gap-2"><UserPlus className="w-4 h-4"/> Allow</button></div><p className="text-[11px] text-zinc-600 mt-2">Expiry is optional. Without it, access remains until you revoke it.</p></section>
 <section><div className="flex items-center justify-between mb-4"><h2 className="font-bold">Approved accounts</h2><span className="text-xs text-zinc-500">{grants.length} viewers</span></div><div className="glass rounded-3xl divide-y divide-white/[.05]">{grants.length?grants.map(g=><div key={g.id} className="flex items-center gap-3 p-4"><div className="w-10 h-10 rounded-full bg-gradient-to-br from-violet-500 to-indigo-500 grid place-items-center font-black">{(g.user.display_name||"U")[0]}</div><div className="flex-1 min-w-0"><p className="font-semibold text-sm truncate">{g.user.display_name}</p><p className="text-xs text-zinc-500">@{g.user.unique_handle}{g.expires_at?` · expires ${new Date(g.expires_at).toLocaleDateString()}`:" · no expiry"}</p></div><button onClick={()=>revoke(g.user_id)} className="p-2.5 rounded-xl text-zinc-500 hover:text-red-400 hover:bg-red-500/10"><Trash2 className="w-4 h-4"/></button></div>):<div className="py-12 text-center"><Lock className="mx-auto text-zinc-700 mb-3"/><p className="text-sm text-zinc-500">No viewers approved yet</p></div>}</div></section></>}
 </div></main><style jsx global>{`.input{width:100%;height:46px;border:1px solid rgba(255,255,255,.08);background:rgba(24,24,27,.8);border-radius:.8rem;padding:.7rem 1rem;font-size:.875rem;outline:none}.input:focus{border-color:#8b5cf6}`}</style></div>}
function Choice({active,icon,title,text,onClick}:{active:boolean,icon:ReactNode,title:string,text:string,onClick:()=>void}){return <button onClick={onClick} className={`p-4 rounded-2xl border text-left flex gap-3 ${active?"border-violet-400 bg-violet-500/10":"border-white/[.08] bg-white/[.02]"}`}><span className={active?"text-violet-300":"text-zinc-500"}>{icon}</span><span className="flex-1"><b className="block text-sm">{title}</b><span className="text-xs text-zinc-500">{text}</span></span>{active&&<Check className="w-4 h-4 text-violet-300"/>}</button>}
