import Link from "next/link";

const sections = [
  { title: "1. Acceptance and scope", body: ["These Terms apply when you access or use the platform, including its video, live-streaming, channel, comments, creator analytics, membership, course and monetization features. By creating an account or using the service, you agree to these Terms and any product or safety rules displayed in the service."] },
  { title: "2. Who may use the service", body: ["You must be at least 13 years old, or the higher minimum age required in your country. If you are under 18, you confirm that a parent or legal guardian has reviewed and accepted these Terms for you. A parent or guardian who permits a minor to use the service is responsible for that minor’s activity.", "If you use the service for a company or organisation, you confirm that you are authorised to accept these Terms on its behalf."] },
  { title: "3. Accounts and security", body: ["Provide accurate information, keep your credentials confidential and promptly report suspected unauthorised access. You are responsible for activity performed through your account. We may require identity, age, tax or payment verification before enabling sensitive or paid features."] },
  { title: "4. Permission to use the service", body: ["We grant you a personal, limited, non-exclusive, non-transferable and revocable permission to use the service as provided. You may not copy, sell, reverse engineer, interfere with or commercially exploit the service except where a feature or applicable law expressly permits it."] },
  { title: "5. Your content and licence", body: ["You retain ownership of videos, audio, thumbnails, comments and other content you submit. You must own the content or have every permission needed to upload and monetize it.", "By submitting content, you grant us a worldwide, non-exclusive, royalty-free, sublicensable and transferable licence to host, store, reproduce, transcode, adapt for technical compatibility, distribute, display, perform and promote that content only to operate, secure, improve and market the service. Other users may access and share your content only through features we provide. The licence ends within a commercially reasonable time after deletion, except for backups, legal retention and content already shared where continued retention is legally permitted."] },
  { title: "6. Prohibited conduct and content", body: ["Do not upload or promote illegal, infringing, hateful, harassing, sexually exploitative, child-endangering, violent-extremist, deceptive, malicious, privacy-invasive or dangerously harmful material. Do not impersonate others, distribute spam or malware, harvest personal data, bypass access controls, scrape without permission, misuse reporting tools or interfere with platform security.", "Buying or artificially generating views, watch time, likes, comments or followers is prohibited. Coordinated engagement manipulation, bots, repeated self-viewing and other invalid traffic may be excluded from analytics and earnings."] },
  { title: "7. Copyright and third-party rights", body: ["Respect copyright, trademark, publicity, privacy and other third-party rights. We may remove content after a valid legal complaint and may restrict repeat infringers. Rights complaints must identify the protected work, challenged content, contact details and the complainant’s authority to act."] },
  { title: "8. Monetization and creator earnings", body: ["Eligibility thresholds do not guarantee approval or continued monetization. Earnings displayed in Creator analytics are estimates until valid-traffic review, policy review, transaction reconciliation, identity verification, tax compliance and payout processing are complete.", "We may adjust, withhold or reverse amounts connected to fraud, invalid traffic, refunds, chargebacks, rights disputes, legal obligations or policy violations. You are responsible for taxes and accurate payout information. Payment timing, payout minimums and revenue rates may be provided separately and may change prospectively."] },
  { title: "9. Moderation, suspension and termination", body: ["We may limit visibility, remove content, disable features, suspend monetization or terminate access when reasonably necessary to enforce these Terms, protect users or the service, investigate abuse, comply with law or prevent harm. Where practical and lawful, we will provide a reason and a way to request review. You may stop using the service and request account deletion, subject to legal and operational retention."] },
  { title: "10. Service changes and availability", body: ["Features, eligibility rules and supported devices may change. We may update, suspend or discontinue parts of the service for security, legal, technical or business reasons. We will provide reasonable notice of material adverse changes when practical, except in urgent circumstances."] },
  { title: "11. Third-party services", body: ["The service may use or link to independent streaming, storage, authentication, payment or other providers. Their terms and privacy practices may apply. We are not responsible for third-party sites or services we do not control."] },
  { title: "12. Disclaimers and liability", body: ["To the extent permitted by law, the service is provided “as is” and “as available”. We do not guarantee uninterrupted operation, particular audience results, revenue, content availability or error-free analytics. Nothing in these Terms excludes rights or liability that cannot legally be excluded.", "To the extent permitted by law, we are not liable for indirect, incidental, special, consequential or punitive loss, lost profits, lost data or lost business opportunities arising from use of the service."] },
  { title: "13. Responsibility for claims", body: ["To the extent permitted by law, business users and creators agree to reimburse reasonable losses and costs resulting from their unlawful content, violation of these Terms or infringement of another person’s rights. This does not reduce any mandatory consumer protection available to you."] },
  { title: "14. Changes and applicable law", body: ["We may revise these Terms to reflect product, legal, safety or security changes. Material updates will be communicated in the app or by another reasonable method. If you do not accept an update, stop using the service and remove your content before it takes effect.", "If one provision is unenforceable, the remaining provisions continue. Applicable law and competent courts are determined by mandatory law and the legal entity and jurisdiction identified in the service’s official business details."] },
  { title: "15. Contact", body: ["Questions, complaints, appeals and legal notices may be submitted through the support or reporting option provided in the app. Valid operator name, registered address, grievance contact and jurisdiction-specific disclosures must be published before commercial launch."] },
] as const;

export default function TermsPage() {
  return <main className="min-h-screen bg-[#070707] px-4 py-8 text-white sm:px-6 sm:py-14"><article className="mx-auto max-w-4xl"><nav className="flex items-center justify-between"><Link href="/" className="text-sm text-indigo-400 hover:text-indigo-300">← Home</Link><Link href="/privacy" className="text-sm text-zinc-400 hover:text-white">Privacy Policy</Link></nav><header className="mt-10 border-b border-white/[.08] pb-10"><p className="text-xs font-bold uppercase tracking-[.22em] text-indigo-400">Legal</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Terms and Conditions</h1><p className="mt-4 text-sm text-zinc-500">Effective: 28 August 2026 · Last updated: 28 August 2026</p><p className="mt-7 max-w-3xl leading-7 text-zinc-300">These Terms explain the rules for viewers, creators and businesses using the platform. Please read them carefully before using, uploading or monetizing content.</p></header><div className="mt-10 space-y-9">{sections.map((section) => <section key={section.title}><h2 className="text-lg font-bold text-zinc-100 sm:text-xl">{section.title}</h2><div className="mt-3 space-y-3">{section.body.map((paragraph) => <p key={paragraph} className="leading-7 text-zinc-400">{paragraph}</p>)}</div></section>)}</div><aside className="mt-12 rounded-2xl border border-amber-500/20 bg-amber-500/[.06] p-5 text-sm leading-6 text-amber-100/80">Launch requirement: replace the operator placeholders with the registered business name, address, grievance contact, payout terms and governing jurisdiction, then obtain qualified legal review for every country where the service operates.</aside></article></main>;
}
