import Link from "next/link";

const sections = [
  { title: "1. Scope", body: ["This Privacy Policy explains how information is collected, used, disclosed and protected when you use the platform as a viewer, creator, member or course participant. It applies to the website, applications and related creator and support tools that link to this Policy."] },
  { title: "2. Information you provide", body: ["We collect account and profile information such as your name, handle, email address, profile images, bio, language and location when provided. Optional birth date is used to calculate an age range for aggregated creator analytics; creators do not receive your birth date.", "We process videos, live streams, audio, thumbnails, titles, descriptions, comments, messages, reports, course material and other content you submit. Creator monetization may require payment, tax, identity or bank details through us or an authorised payment provider."] },
  { title: "3. Information collected through use", body: ["We collect searches, videos viewed, watch duration, playback progress, likes, comments, follows, subscriptions, uploads, visibility choices, live participation, purchases and interactions with features.", "Technical information may include IP address or a protected hash derived from it, session and device identifiers, browser and operating-system details, language, approximate region, referral page, timestamps, network status, crash data and security logs. Cookies, local storage and similar technologies may keep you signed in, remember settings, measure performance and prevent abuse."] },
  { title: "4. How information is used", body: ["We use information to provide accounts and playback, process uploads and live streams, remember progress and settings, operate search and discovery, enable community features, answer support requests and communicate service or security updates.", "We also use it to calculate views, watch time, engagement, creator eligibility and estimated earnings; detect fraud, invalid traffic, spam, copyright or safety violations; maintain reliability; understand product performance; comply with law; and improve features."] },
  { title: "5. Creator analytics and age ranges", body: ["Creators may see aggregate views, watch time, likes, comments, revenue estimates and audience age ranges for their own content. A range is shown only after a minimum audience threshold is met. Creator analytics do not disclose a viewer’s birth date, email, device identifier, IP information, individual viewing history or identity. Aggregates and estimates may be delayed, filtered or corrected after invalid-traffic review."] },
  { title: "6. Public information", body: ["Content marked public, along with your channel name, handle, profile image, follower counts, comments and visible interactions, can be seen and reshared by others and may appear in search results. Private or restricted content is processed only for authorised delivery, safety, security and legal purposes, but no online sharing setting can eliminate every risk of copying by recipients."] },
  { title: "7. When information is shared", body: ["We share information with infrastructure, hosting, video streaming, content delivery, security, analytics, customer-support and payment providers that process it under instructions and appropriate safeguards. We may share information with your consent, at your direction, or with a channel or organisation you administer.", "Information may also be disclosed to comply with law or a valid legal request; enforce terms; investigate fraud, security or rights violations; protect users or the public; or support a merger, financing, acquisition or sale subject to appropriate safeguards. We do not claim to sell personal information. If advertising or a legal definition of “sale” or “sharing” later applies, required disclosures and controls must be added before that activity launches."] },
  { title: "8. Data retention", body: ["We retain information for as long as needed to provide the service and for legitimate security, fraud-prevention, dispute, accounting and legal purposes. Retention depends on data type and sensitivity. Deleted content or accounts may remain temporarily in backups and may be retained longer when required by law, to resolve rights claims or to prevent abuse. Aggregated or de-identified statistics may be retained where they no longer identify you."] },
  { title: "9. Security", body: ["We use access controls, encryption in transit, credential protection, monitoring, rate limits, backups and other organisational and technical safeguards appropriate to the service. No storage or transmission system is completely secure, so protect your credentials and notify support if you suspect account misuse."] },
  { title: "10. Your controls and rights", body: ["Depending on product availability and local law, you may review or edit profile details, omit optional birth date, manage content visibility, remove content, log out, request account deletion, or ask for access, correction, deletion, portability, restriction or objection. Some data may remain where retention is legally required or necessary for security, fraud prevention or rights claims.", "Privacy requests may require identity verification. Authorised agents may be required to provide proof of authority. You may also complain to the data-protection authority available in your region."] },
  { title: "11. Children", body: ["The general service is not directed to children under 13 or the higher digital-consent age in their country. Minors must have any consent required from a parent or guardian. If we learn that personal information was collected from a child without required permission, we will take reasonable steps to delete or restrict it. A child-directed experience must not launch without a separate child privacy design and notice."] },
  { title: "12. International processing", body: ["Service providers may process information outside your state or country. Where required, we use recognised transfer mechanisms and safeguards. The countries, legal entity and transfer mechanism relevant to production operations must be identified in the final launch disclosures."] },
  { title: "13. Third-party services", body: ["Links, embedded tools, payment processors and independent services may collect information under their own policies. This Policy does not govern services that we do not control. Review their privacy terms before providing information."] },
  { title: "14. Changes and contact", body: ["We may update this Policy when the service, law or data practices change. The updated date will be shown here, and material changes will receive reasonable notice in the app or by another appropriate method.", "Privacy questions and requests may be submitted through the support option in the app. Before commercial launch, the service must publish its legal operator, registered address, privacy or grievance contact, response process and any region-specific notices."] },
] as const;

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#070707] px-4 py-8 text-white sm:px-6 sm:py-14"><article className="mx-auto max-w-4xl"><nav className="flex items-center justify-between"><Link href="/" className="text-sm text-emerald-400 hover:text-emerald-300">← Home</Link><Link href="/terms" className="text-sm text-zinc-400 hover:text-white">Terms and Conditions</Link></nav><header className="mt-10 border-b border-white/[.08] pb-10"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-400">Privacy</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Privacy Policy</h1><p className="mt-4 text-sm text-zinc-500">Effective: 28 August 2026 · Last updated: 28 August 2026</p><p className="mt-7 max-w-3xl leading-7 text-zinc-300">This Policy describes the information used to provide video, community and creator features, and the choices available to you.</p></header><div className="mt-10 space-y-9">{sections.map((section) => <section key={section.title}><h2 className="text-lg font-bold text-zinc-100 sm:text-xl">{section.title}</h2><div className="mt-3 space-y-3">{section.body.map((paragraph) => <p key={paragraph} className="leading-7 text-zinc-400">{paragraph}</p>)}</div></section>)}</div><aside className="mt-12 rounded-2xl border border-amber-500/20 bg-amber-500/[.06] p-5 text-sm leading-6 text-amber-100/80">Launch requirement: add the registered data controller, contact address, grievance/privacy officer, actual vendors, retention schedule and region-specific rights after legal review. The policy must always match the data the production system actually collects.</aside></article></main>;
}
