"use client";
import { useEffect, useState } from "react";
import { Crown, Loader2, Plus, Users, X, Zap } from "lucide-react";
import { useRouter } from "next/navigation";
import DashboardSidebar from "@/components/DashboardSidebar";
import { buildApiUrl } from "@/lib/api";

export default function Memberships(){
 const router=useRouter(); const [channel,setChannel]=useState<any>(); const [members,setMembers]=useState<any[]>([]); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [form,setForm]=useState({name:"",description:"",price:"199",benefits:"Members-only live chat\nEarly access\nLoyalty badge"});
 const auth=()=>({Authorization:`Bearer ${localStorage.getItem("accessToken")}`});
 const load=async()=>{const user=JSON.parse(localStorage.getItem("user")||"null");if(!user){router.push("/login");return}const c=await fetch(buildApiUrl(`/api/channels/${user.unique_handle}`));if(c.ok)setChannel((await c.json()).channel);const m=await fetch(buildApiUrl("/api/channels/me/members"),{headers:auth()});if(m.ok)setMembers((await m.json()).memberships)};
 useEffect(()=>{load()},[]);
 const toggle=async()=>{const r=await fetch(buildApiUrl("/api/channels/me"),{method:"PATCH",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({membership_enabled:!channel.membership_enabled})});if(r.ok)setChannel((await r.json()).channel)};
 const create=async()=>{setSaving(true);const r=await fetch(buildApiUrl("/api/channels/me/tiers"),{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({name:form.name,description:form.description,price_amount:Math.round(Number(form.price)*100),currency:"INR",benefits:form.benefits.split("\n").filter(Boolean)})});if(r.ok){setOpen(false);await load()}setSaving(false)};
 if(!channel)return <div className="min-h-screen bg-[#080808] text-white"><DashboardSidebar/><main className="md:ml-60 min-h-screen grid place-items-center"><div className="text-center"><Crown className="w-12 h-12 text-amber-400 mx-auto mb-4"/><h1 className="font-bold text-xl">Create your channel first</h1><button onClick={()=>router.push("/dashboard/channel")} className="mt-4 bg-white text-black px-5 py-2.5 rounded-xl font-bold text-sm">Open channel studio</button></div></main></div>;
 return <div className="min-h-screen bg-[#080808] text-white"><DashboardSidebar/><main className="md:ml-60 pb-28"><header className="h-16 px-5 md:px-8 border-b border-white/[.06] flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[.2em] text-amber-400 font-bold">Earn with PodLive</p><h1 className="font-bold">Memberships</h1></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 bg-white text-black rounded-xl px-4 py-2 text-sm font-bold"><Plus className="w-4 h-4"/> New tier</button></header><div className="p-5 md:p-8 max-w-6xl mx-auto space-y-6">
 <section className="rounded-[28px] p-6 md:p-8 overflow-hidden relative border border-amber-300/20 bg-gradient-to-br from-amber-500/15 via-orange-500/5 to-transparent"><div className="absolute -right-12 -top-20 w-56 h-56 bg-amber-400/10 blur-3xl rounded-full"/><div className="relative flex flex-col md:flex-row md:items-center justify-between gap-5"><div><div className="flex items-center gap-2 text-amber-300 mb-2"><Crown className="w-5 h-5"/><span className="text-xs font-black uppercase tracking-widest">Channel memberships</span></div><h2 className="text-2xl font-black">Turn your biggest fans into members</h2><p className="text-zinc-400 mt-2 max-w-xl text-sm">Offer badges, private podcasts, early access and exclusive community benefits.</p></div><button onClick={toggle} className={`px-5 py-3 rounded-xl font-bold text-sm ${channel.membership_enabled?"bg-emerald-400 text-black":"bg-white text-black"}`}>{channel.membership_enabled?"Memberships active":"Enable memberships"}</button></div></section>
 <div className="grid lg:grid-cols-[1fr_320px] gap-6"><section><div className="flex items-center justify-between mb-4"><h2 className="font-bold">Your tiers</h2><span className="text-xs text-zinc-500">{channel.membership_tiers?.length||0} plans</span></div><div className="grid sm:grid-cols-2 gap-4">{channel.membership_tiers?.map((t:any,i:number)=><div key={t.id} className="glass rounded-3xl p-6 relative overflow-hidden"><div className="absolute top-0 inset-x-0 h-1" style={{background:i%2?channel.accent_color:channel.primary_color}}/><div className="flex justify-between"><div className="w-10 h-10 rounded-xl bg-amber-400/10 grid place-items-center"><Crown className="w-5 h-5 text-amber-400"/></div><span className="text-xs text-emerald-400">Active</span></div><h3 className="font-black text-xl mt-5">{t.name}</h3><p className="text-3xl font-black mt-2">₹{(t.price_amount/100).toLocaleString()}<span className="text-xs text-zinc-500 font-medium"> / month</span></p><p className="text-sm text-zinc-400 mt-3">{t.description}</p><ul className="mt-5 space-y-2">{(t.benefits||[]).map((b:string)=><li key={b} className="flex gap-2 text-sm text-zinc-300"><Zap className="w-4 h-4 text-amber-400 shrink-0"/>{b}</li>)}</ul></div>)}{!channel.membership_tiers?.length&&<button onClick={()=>setOpen(true)} className="min-h-64 rounded-3xl border border-dashed border-white/15 grid place-items-center text-zinc-500 hover:text-white"><div><Plus className="mx-auto mb-2"/><p className="text-sm">Create your first membership tier</p></div></button>}</div></section><aside><h2 className="font-bold mb-4">Recent members</h2><div className="glass rounded-3xl p-3">{members.length?members.slice(0,8).map((m:any)=><div key={m.id} className="flex items-center gap-3 p-3"><div className="w-9 h-9 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 grid place-items-center font-black text-xs">{(m.member.display_name||"M").slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold truncate">{m.member.display_name}</p><p className="text-xs text-zinc-500">{m.tier.name}</p></div><span className={`text-[10px] px-2 py-1 rounded-full ${m.status==='active'?'bg-emerald-500/10 text-emerald-400':'bg-amber-500/10 text-amber-400'}`}>{m.status}</span></div>):<div className="py-12 text-center"><Users className="w-8 h-8 mx-auto text-zinc-700 mb-2"/><p className="text-sm text-zinc-500">Members will appear here</p></div>}</div></aside></div>
 </div></main>{open&&<div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm grid place-items-center p-4" onClick={()=>setOpen(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-lg bg-[#141416] border border-white/10 rounded-3xl p-6 relative"><button onClick={()=>setOpen(false)} className="absolute right-5 top-5 text-zinc-500"><X/></button><h2 className="text-xl font-black">Create membership tier</h2><p className="text-sm text-zinc-500 mt-1 mb-6">Give this tier a clear value for your fans.</p><div className="space-y-4"><Input label="Tier name" value={form.name} set={(v:string)=>setForm({...form,name:v})} placeholder="Super Listener"/><Input label="Monthly price (₹)" value={form.price} set={(v:string)=>setForm({...form,price:v})}/><label><span className="label">Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={2} className="input resize-none"/></label><label><span className="label">Benefits — one per line</span><textarea value={form.benefits} onChange={e=>setForm({...form,benefits:e.target.value})} rows={5} className="input resize-none"/></label><button onClick={create} disabled={!form.name||saving} className="w-full py-3 bg-amber-400 text-black rounded-xl font-black disabled:opacity-50">{saving?<Loader2 className="animate-spin mx-auto"/>:"Create tier"}</button></div></div></div>}<style jsx global>{`.label{display:block;font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#a1a1aa;margin-bottom:.5rem}.input{width:100%;border:1px solid rgba(255,255,255,.08);background:rgba(24,24,27,.65);border-radius:.8rem;padding:.75rem 1rem;font-size:.875rem;outline:none}.input:focus{border-color:#fbbf24}`}</style></div>
}
function Input({label,value,set,placeholder}:{label:string,value:string,set:(v:string)=>void,placeholder?:string}){return <label><span className="label">{label}</span><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="input"/></label>}
