"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, BookOpen, Check, ChevronDown, Globe2, GripVertical, IndianRupee, Loader2, Lock, Plus, Radio, Settings2, Sparkles, Video } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import DashboardSidebar from "@/components/DashboardSidebar";
import { buildApiUrl } from "@/lib/api";

export default function CourseEditor(){const {id}=useParams();const router=useRouter();const [course,setCourse]=useState<any>();const [tab,setTab]=useState("curriculum");const [saving,setSaving]=useState(false);const [sectionTitle,setSectionTitle]=useState("");const [lessonFor,setLessonFor]=useState<string>();const [lesson,setLesson]=useState({title:"",kind:"video",video_url:"",is_preview:false});const auth=()=>({Authorization:`Bearer ${localStorage.getItem("accessToken")}`});const load=()=>fetch(buildApiUrl(`/api/courses/${id}`),{headers:auth()}).then(r=>r.json()).then(d=>setCourse(d.course));useEffect(()=>{load()},[id]);
 const save=async(extra={})=>{setSaving(true);const r=await fetch(buildApiUrl(`/api/courses/${id}`),{method:"PATCH",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({...course,...extra})});if(r.ok)setCourse((await r.json()).course);setSaving(false)};
 const addSection=async()=>{if(!sectionTitle)return;await fetch(buildApiUrl(`/api/courses/${id}/sections`),{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({title:sectionTitle})});setSectionTitle("");load()};
 const addLesson=async(sectionId:string)=>{if(!lesson.title)return;await fetch(buildApiUrl(`/api/courses/${id}/sections/${sectionId}/lessons`),{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({...lesson,is_published:true})});setLesson({title:"",kind:"video",video_url:"",is_preview:false});setLessonFor(undefined);load()};
 if(!course)return <div className="min-h-screen bg-[#080808] grid place-items-center"><Loader2 className="animate-spin text-cyan-400"/></div>;
 return <div className="min-h-screen bg-[#080808] text-white"><DashboardSidebar/><main className="md:ml-60 pb-28"><header className="min-h-16 px-5 md:px-8 border-b border-white/[.06] flex items-center gap-3 py-3"><button onClick={()=>router.push("/dashboard/courses")}><ArrowLeft/></button><div className="min-w-0 flex-1"><p className="text-[10px] uppercase tracking-widest text-cyan-400">Course builder</p><input value={course.title} onChange={e=>setCourse({...course,title:e.target.value})} className="font-black bg-transparent outline-none w-full"/></div><span className={`hidden sm:block text-xs px-3 py-1.5 rounded-full ${course.status==='published'?'bg-emerald-400/15 text-emerald-400':'bg-zinc-800 text-zinc-400'}`}>{course.status}</span><button onClick={()=>save()} className="px-4 py-2 border border-white/10 rounded-xl text-sm font-bold">{saving?<Loader2 className="w-4 h-4 animate-spin"/>:"Save"}</button><button onClick={()=>save({status:course.status==='published'?'draft':'published'})} className="px-4 py-2 bg-cyan-400 text-black rounded-xl text-sm font-black">{course.status==='published'?"Unpublish":"Publish"}</button></header>
 <nav className="px-5 md:px-8 border-b border-white/[.06] flex gap-6">{["curriculum","details","pricing","design"].map(t=><button key={t} onClick={()=>setTab(t)} className={`py-4 text-sm capitalize border-b-2 ${tab===t?'border-cyan-400 text-white':'border-transparent text-zinc-500'}`}>{t}</button>)}</nav><div className="p-5 md:p-8 max-w-5xl mx-auto">
 {tab==='curriculum'&&<div><div className="flex items-center justify-between mb-5"><div><h2 className="text-xl font-black">Course curriculum</h2><p className="text-sm text-zinc-500">Mix recorded videos, live classes, articles and downloads.</p></div></div><div className="space-y-4">{course.sections.map((s:any)=><div key={s.id} className="glass rounded-3xl overflow-hidden"><div className="p-4 flex items-center gap-3 bg-white/[.025]"><GripVertical className="text-zinc-600"/><BookOpen className="text-cyan-400"/><b className="flex-1">{s.title}</b><span className="text-xs text-zinc-500">{s.lessons.length} lessons</span><ChevronDown/></div><div className="divide-y divide-white/[.05]">{s.lessons.map((l:any)=><div key={l.id} className="p-4 pl-12 flex items-center gap-3">{l.kind==='live'?<Radio className="w-4 h-4 text-red-400"/>:<Video className="w-4 h-4 text-violet-400"/>}<span className="flex-1 text-sm">{l.title}</span>{l.is_preview?<span className="text-[10px] text-cyan-400">FREE PREVIEW</span>:<Lock className="w-3.5 h-3.5 text-zinc-600"/>}</div>)}</div>{lessonFor===s.id?<div className="p-4 bg-cyan-500/[.04] grid sm:grid-cols-[1fr_130px] gap-3"><input className="input" value={lesson.title} onChange={e=>setLesson({...lesson,title:e.target.value})} placeholder="Lesson title"/><select className="input" value={lesson.kind} onChange={e=>setLesson({...lesson,kind:e.target.value})}><option value="video">Video</option><option value="live">Live class</option><option value="article">Article</option><option value="resource">Download</option></select><input className="input sm:col-span-2" value={lesson.video_url} onChange={e=>setLesson({...lesson,video_url:e.target.value})} placeholder="Video/resource URL or Live session ID"/><label className="text-xs text-zinc-400 flex gap-2"><input type="checkbox" checked={lesson.is_preview} onChange={e=>setLesson({...lesson,is_preview:e.target.checked})}/> Free preview</label><button onClick={()=>addLesson(s.id)} className="bg-cyan-400 text-black rounded-xl py-2 font-bold text-sm">Add lesson</button></div>:<button onClick={()=>setLessonFor(s.id)} className="m-3 ml-12 text-xs text-cyan-400 flex gap-1"><Plus className="w-4 h-4"/> Add lesson</button>}</div>)}<div className="flex gap-2"><input value={sectionTitle} onChange={e=>setSectionTitle(e.target.value)} className="input flex-1" placeholder="New section title"/><button onClick={addSection} className="px-5 bg-white text-black rounded-xl font-bold text-sm">Add section</button></div></div></div>}
 {tab==='details'&&<Panel title="Course details" icon={<Settings2/>}><Field label="Subtitle" value={course.subtitle||""} set={(v:string)=>setCourse({...course,subtitle:v})}/><Area label="Full description" value={course.description||""} set={(v:string)=>setCourse({...course,description:v})}/><div className="grid sm:grid-cols-2 gap-4"><Field label="Category" value={course.category||""} set={(v:string)=>setCourse({...course,category:v})}/><Field label="Language" value={course.language} set={(v:string)=>setCourse({...course,language:v})}/><Field label="Thumbnail URL" value={course.thumbnail_url||""} set={(v:string)=>setCourse({...course,thumbnail_url:v})}/><Field label="Trailer URL" value={course.trailer_url||""} set={(v:string)=>setCourse({...course,trailer_url:v})}/></div><button onClick={()=>save()} className="btn">Save details</button></Panel>}
 {tab==='pricing'&&<Panel title="Pricing & access" icon={<IndianRupee/>}><div className="grid sm:grid-cols-2 gap-4"><Field label="Sale price (₹)" value={String(course.price_amount/100)} set={(v:string)=>setCourse({...course,price_amount:Math.round(Number(v)*100)})}/><Field label="Original price (₹)" value={String((course.compare_price_amount||0)/100)} set={(v:string)=>setCourse({...course,compare_price_amount:Math.round(Number(v)*100)})}/></div><p className="text-xs text-zinc-500">Set ₹0 for a free course. Paid orders unlock only after verified payment webhook.</p><button onClick={()=>save()} className="btn">Save pricing</button></Panel>}
 {tab==='design'&&<Panel title="Course storefront" icon={<Sparkles/>}><div className="grid sm:grid-cols-2 gap-4"><Color label="Primary color" value={course.theme?.primaryColor||'#06B6D4'} set={(v:string)=>setCourse({...course,theme:{...course.theme,primaryColor:v}})}/><label><span className="label">Style</span><select value={course.theme?.style||'modern'} onChange={e=>setCourse({...course,theme:{...course.theme,style:e.target.value}})} className="input"><option>modern</option><option>academic</option><option>playful</option><option>minimal</option></select></label></div><div className="mt-5 aspect-[16/7] rounded-3xl p-7 flex flex-col justify-end" style={{background:`linear-gradient(135deg,${course.theme?.primaryColor||'#06B6D4'},#18181b)`}}><p className="text-xs uppercase tracking-widest">{course.category}</p><h3 className="text-3xl font-black mt-2">{course.title}</h3><p className="opacity-70">{course.subtitle}</p></div><button onClick={()=>save()} className="btn">Save design</button></Panel>}
 </div></main><style jsx global>{`.label{display:block;font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#a1a1aa;margin-bottom:.5rem}.input{width:100%;border:1px solid rgba(255,255,255,.08);background:#18181b;border-radius:.8rem;padding:.75rem 1rem;font-size:.875rem;outline:none}.input:focus{border-color:#22d3ee}.btn{background:#22d3ee;color:#000;padding:.7rem 1.25rem;border-radius:.75rem;font-size:.875rem;font-weight:800}`}</style></div>}
function Panel({title,icon,children}:{title:string,icon:React.ReactNode,children:React.ReactNode}){return <div className="glass rounded-3xl p-6 space-y-5"><h2 className="font-black text-xl flex gap-2 text-cyan-300">{icon}{title}</h2>{children}</div>}function Field({label,value,set}:{label:string,value:string,set:(v:string)=>void}){return <label><span className="label">{label}</span><input value={value} onChange={e=>set(e.target.value)} className="input"/></label>}function Area({label,value,set}:{label:string,value:string,set:(v:string)=>void}){return <label><span className="label">{label}</span><textarea rows={7} value={value} onChange={e=>set(e.target.value)} className="input resize-none"/></label>}function Color({label,value,set}:{label:string,value:string,set:(v:string)=>void}){return <label><span className="label">{label}</span><div className="flex gap-2"><input type="color" value={value} onChange={e=>set(e.target.value)} className="w-12 h-11"/><input value={value} onChange={e=>set(e.target.value)} className="input"/></div></label>}
