"use client";
import { useEffect, useState } from "react";
import { BookOpen, IndianRupee, Loader2, Plus, Sparkles, Users } from "lucide-react";
import { useRouter } from "next/navigation";
import DashboardSidebar from "@/components/DashboardSidebar";
import { buildApiUrl } from "@/lib/api";

export default function Courses(){const router=useRouter();const [courses,setCourses]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [creating,setCreating]=useState(false);const token=()=>localStorage.getItem("accessToken");useEffect(()=>{fetch(buildApiUrl("/api/courses/mine"),{headers:{Authorization:`Bearer ${token()}`}}).then(r=>r.json()).then(d=>setCourses(d.courses||[])).finally(()=>setLoading(false))},[]);
 const create=async()=>{setCreating(true);const r=await fetch(buildApiUrl("/api/courses"),{method:"POST",headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json"},body:JSON.stringify({title:"Untitled course",language:"Hindi",category:"Education",price_amount:0})});const d=await r.json();if(r.ok)router.push(`/dashboard/courses/${d.course.id}`);else setCreating(false)};
 return <div className="min-h-screen bg-[#080808] text-white"><DashboardSidebar/><main className="md:ml-60 pb-28"><header className="h-16 px-5 md:px-8 border-b border-white/[.06] flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[.2em] text-cyan-400 font-bold">Teacher Studio</p><h1 className="font-bold">My courses</h1></div><button onClick={create} disabled={creating} className="bg-white text-black px-4 py-2 rounded-xl font-bold text-sm flex items-center gap-2">{creating?<Loader2 className="w-4 h-4 animate-spin"/>:<Plus className="w-4 h-4"/>} New course</button></header><div className="p-5 md:p-8 max-w-6xl mx-auto"><section className="rounded-[30px] p-7 md:p-9 bg-gradient-to-br from-cyan-500/15 via-blue-500/[.06] to-transparent border border-cyan-300/15 mb-7"><Sparkles className="text-cyan-300"/><h2 className="text-2xl md:text-3xl font-black mt-4">Teach once. Inspire thousands.</h2><p className="text-zinc-400 text-sm mt-2 max-w-xl">Build video courses, live classes, resources and certificates—all under your own channel brand.</p></section>{loading?<Loader2 className="animate-spin mx-auto mt-20 text-cyan-400"/>:courses.length?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{courses.map(c=><button key={c.id} onClick={()=>router.push(`/dashboard/courses/${c.id}`)} className="glass rounded-3xl overflow-hidden text-left group"><div className="aspect-[16/8] bg-gradient-to-br from-cyan-500/20 to-violet-500/20 grid place-items-center relative">{c.thumbnail_url?<img src={c.thumbnail_url} className="w-full h-full object-cover" alt=""/>:<BookOpen className="w-12 h-12 text-white/20"/>}<span className={`absolute top-3 right-3 px-2.5 py-1 rounded-full text-[10px] uppercase font-black ${c.status==='published'?'bg-emerald-400 text-black':'bg-black/60'}`}>{c.status}</span></div><div className="p-5"><h3 className="font-black text-lg group-hover:text-cyan-300">{c.title}</h3><p className="text-xs text-zinc-500 mt-1">{c.category||"Uncategorized"} · {c.language}</p><div className="grid grid-cols-3 gap-2 mt-5 text-xs"><span className="flex gap-1 text-zinc-400"><BookOpen className="w-3.5 h-3.5"/>{c._count?.sections||0} sections</span><span className="flex gap-1 text-zinc-400"><Users className="w-3.5 h-3.5"/>{c.enrollment_count||0}</span><span className="flex gap-1 text-zinc-400"><IndianRupee className="w-3.5 h-3.5"/>{c.price_amount/100}</span></div></div></button>)}</div>:<button onClick={create} className="w-full py-20 rounded-3xl border border-dashed border-white/15 text-zinc-500 hover:text-white"><Plus className="mx-auto mb-3"/><p>Create your first course</p></button>}</div></main></div>}
