"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Check, ChevronDown, ExternalLink, Languages, Mic, Play, Radio, ShieldCheck, Sparkles, Users } from "lucide-react";
import { detectLanguage, saveLanguage, type SupportedLanguage } from "@/lib/language";

const copy = {
  hi: {
    about: "परिचय", plans: "प्लान", projects: "PodLive के अन्य प्रोजेक्ट", signIn: "लॉग इन", signUp: "साइन अप",
    badge: "भारत का वीडियो शेयरिंग और लाइव पॉडकास्ट मंच", title: "असीमित मनोरंजन।", titleAccent: "हर आवाज़ लाइव।",
    intro: "टेक्नोलॉजी, फिल्में, कॉमेडी, शिक्षा, फाइनेंस, गेमिंग, सामान्य ज्ञान, पॉडकास्ट, ब्लॉग और लाइव मनोरंजन—सब एक जगह।",
    start: "अभी शुरू करें", free: "मुफ़्त अकाउंट बनाएँ। प्रीमियम प्लान वैकल्पिक हैं।", what: "PodLive क्या है?",
    stage: "भारत की कहानियों, हुनर और बातचीत का डिजिटल मंच।", aboutBody: "PodLive वीडियो, लाइव पॉडकास्ट, सीखने वाले कंटेंट और कम्युनिटी के माध्यम से creators और viewers को जोड़ता है। मोबाइल, टैबलेट या ब्राउज़र से देखें, बनाएँ, लाइव जाएँ और अपना चैनल बढ़ाएँ।",
    founded: "संस्थापक Amitesh Kumar Yadav; सह-संस्थापक Adarsh Kumar और Aman Nawhar।", premium: "प्रीमियम प्लान", more: "ज़्यादा देखें। ज़्यादा बनाएँ।", payment: "मासिक प्लान। सुरक्षित सत्यापन के बाद ही भुगतान सक्रिय होगा।", choose: "चुनें", month: "महीना", faqTitle: "अक्सर पूछे जाने वाले सवाल", faqHeading: "सवाल? जवाब यहाँ है।"
  },
  en: {
    about: "About", plans: "Plans", projects: "Other Projects of PodLive", signIn: "Sign in", signUp: "Sign up",
    badge: "India-first video sharing and live podcast platform", title: "Unlimited entertainment.", titleAccent: "Every voice, live.",
    intro: "Technology, movies, comedy, education, finance, gaming, general knowledge, podcasts, blogs and live fun—all in one place.",
    start: "Get started", free: "Create a free account. Premium plans are optional.", what: "What is PodLive?",
    stage: "A digital stage for India’s stories, skills and conversations.", aboutBody: "PodLive connects creators and viewers through videos, live podcasts, learning content and communities. Watch, create, go live and grow your channel from a phone, tablet or browser.",
    founded: "Founded by Amitesh Kumar Yadav, with co-founders Adarsh Kumar and Aman Nawhar.", premium: "Premium plans", more: "Watch more. Create more.", payment: "Monthly plans. Payment activates only after secure verification.", choose: "Choose", month: "month", faqTitle: "Frequently asked questions", faqHeading: "Questions? Find answers here."
  }
} as const;

const faq = {
  hi: [["PodLive क्या है?", "PodLive भारत का वीडियो शेयरिंग और लाइव पॉडकास्ट प्लेटफॉर्म है, जहाँ लोग देख सकते हैं, सीख सकते हैं, content बना सकते हैं और community बढ़ा सकते हैं।"], ["PodLive की कीमत क्या है?", "उपलब्ध public content मुफ़्त explore करें। Plus ₹299/महीना और Max ₹599/महीना है।"], ["मैं कहाँ देख सकता हूँ?", "Supported मोबाइल, टैबलेट और desktop browser पर responsive player के साथ देखें।"], ["मैं क्या देख सकता हूँ?", "Technology, movies, comedy, education, finance, gaming, general knowledge, podcasts, blogs और creators के live conversations देखें।"], ["क्या PodLive बच्चों के लिए अच्छा है?", "सामान्य सेवा 13+ users के लिए है। नाबालिगों को guardian की अनुमति चाहिए और माता-पिता को viewing supervise करनी चाहिए।"]],
  en: [["What is PodLive?", "PodLive is an India-first video-sharing and live podcast platform where people can watch, learn, create and build communities."], ["How much does PodLive cost?", "Explore available public content for free. Plus costs ₹299/month and Max costs ₹599/month."], ["Where can I watch?", "Watch with a responsive player on supported phones, tablets and desktop browsers."], ["What can I watch?", "Explore technology, movies, comedy, education, finance, gaming, general knowledge, podcasts, blogs and creators’ live conversations."], ["Is PodLive good for kids?", "The general service is for users aged 13+. Minors need guardian permission and parents should supervise viewing."]]
} as const;

const projects = [
  { name: "IndiaSearch", url: "https://indiasearch.site", hi: "भारतीय users के लिए बनाया गया AI voice search engine", en: "AI voice search engine designed for Indian users" },
  { name: "CHEETCHAT", url: "https://chat.indiasearch.site/", hi: "भारतीय users के लिए बनाया गया all-in-one app", en: "An all-in-one app designed for Indian users" },
  { name: "Arundhati App", url: "https://downloader.indiasearch.site/", hi: "भाषा की बाधा खत्म करने के लिए real-time language translator", en: "A real-time translator designed to remove language barriers" },
] as const;

const plans = [
  { name: "Plus", price: 299, features: { hi: ["बिना विज्ञापन वीडियो", "1080p तक बेहतर quality", "Personalised feed", "ज़्यादा live podcasts"], en: ["Ad-free videos", "Higher quality up to 1080p", "Personalised feed", "More live podcasts"] } },
  { name: "Max", price: 599, features: { hi: ["असीमित ad-free viewing", "सबसे ऊँची उपलब्ध quality", "Personalised feed", "असीमित podcast creation"], en: ["Unlimited ad-free viewing", "Highest available quality", "Personalised feed", "Unlimited podcast creation"] } },
] as const;

export default function MarketingLanding() {
  const [language, setLanguage] = useState<SupportedLanguage>("en");
  const [openFaq, setOpenFaq] = useState(0);
  useEffect(() => {
    const timer = window.setTimeout(() => setLanguage(detectLanguage()), 0);
    return () => window.clearTimeout(timer);
  }, []);
  const text = copy[language];
  const chooseLanguage = (value: SupportedLanguage) => { saveLanguage(value); setLanguage(value); };
  return <div className="min-h-screen overflow-hidden bg-[#050505] text-white">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/80 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-7xl items-center gap-3 px-4 sm:px-6"><Link href="/" className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-red-500 to-fuchsia-600"><Mic className="size-5" /></span><span className="text-lg font-black">PodLive</span></Link><nav className="ml-auto hidden items-center gap-5 text-sm text-zinc-300 lg:flex"><a href="#about">{text.about}</a><a href="#plans">{text.plans}</a><a href="#faq">FAQ</a><details className="group relative"><summary className="cursor-pointer list-none">{text.projects} ▾</summary><div className="absolute right-0 top-8 w-80 rounded-2xl border border-white/10 bg-zinc-950 p-2 shadow-2xl">{projects.map(project=><a key={project.name} href={project.url} target="_blank" rel="noopener noreferrer" className="flex gap-3 rounded-xl p-3 hover:bg-white/[.06]"><ExternalLink className="mt-0.5 size-4 shrink-0 text-red-400"/><span><strong className="text-sm text-white">{project.name}</strong><span className="mt-1 block text-xs leading-5 text-zinc-500">{project[language]}</span></span></a>)}</div></details></nav><label className="relative ml-auto lg:ml-2"><Languages className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-zinc-400"/><select aria-label="Language" value={language} onChange={event=>chooseLanguage(event.target.value as SupportedLanguage)} className="h-10 rounded-lg border border-white/15 bg-black pl-8 pr-2 text-xs"><option value="hi">हिन्दी</option><option value="en">English</option></select></label><Link href="/login" className="hidden rounded-lg px-3 py-2 text-sm font-bold sm:block">{text.signIn}</Link><Link href="/register" className="rounded-lg bg-red-600 px-3 py-2 text-xs font-black sm:text-sm">{text.signUp}</Link></div><div className="border-t border-white/[.06] px-4 py-2 text-center text-[11px] text-zinc-400 lg:hidden"><a href="#projects">{text.projects} ↓</a></div></header>
    <main><section className="relative grid min-h-[92svh] place-items-center px-5 pb-16 pt-32 text-center"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_30%,rgba(220,38,38,.3),transparent_32%),radial-gradient(circle_at_20%_70%,rgba(124,58,237,.2),transparent_30%)]"/><div className="relative mx-auto max-w-5xl"><span className="inline-flex items-center gap-2 rounded-full border border-red-400/25 bg-red-500/10 px-4 py-2 text-xs font-bold text-red-200"><Radio className="size-4"/>{text.badge}</span><h1 className="mt-7 text-4xl font-black leading-[1.05] sm:text-6xl lg:text-8xl">{text.title} <span className="bg-gradient-to-r from-red-400 via-fuchsia-400 to-indigo-400 bg-clip-text text-transparent">{text.titleAccent}</span></h1><p className="mx-auto mt-6 max-w-3xl text-base leading-7 text-zinc-300 sm:text-xl">{text.intro}</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-xl bg-red-600 px-7 font-black"><Play className="size-5 fill-current"/>{text.start}</Link><Link href="/login" className="inline-flex min-h-13 items-center justify-center rounded-xl border border-white/20 bg-white/10 px-7 font-bold">{text.signIn}</Link></div><p className="mt-4 text-xs text-zinc-500">{text.free}</p></div></section>
      <section id="about" className="border-y border-white/[.07] bg-zinc-950 px-5 py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.25em] text-red-400">{text.what}</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">{text.stage}</h2><p className="mt-6 leading-8 text-zinc-400">{text.aboutBody}</p><p className="mt-5 text-sm text-zinc-500">{text.founded}</p></div><div className="grid grid-cols-2 gap-3">{[[Sparkles,"Unlimited discovery"],[Radio,"Live fun"],[Users,"Creator communities"],[ShieldCheck,"Creator control"]].map(([Icon,title])=><div key={String(title)} className="rounded-2xl border border-white/[.08] bg-white/[.03] p-5"><Icon className="size-6 text-red-400"/><h3 className="mt-5 font-bold">{String(title)}</h3></div>)}</div></div></section>
      <section id="projects" className="px-5 py-20"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black sm:text-5xl">{text.projects}</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{projects.map(project=><a key={project.name} href={project.url} target="_blank" rel="noopener noreferrer" className="group rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.06] to-transparent p-6 hover:border-red-400/30"><ExternalLink className="size-5 text-red-400"/><h3 className="mt-8 text-xl font-black">{project.name}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{project[language]}</p></a>)}</div></div></section>
      <section id="plans" className="border-y border-white/[.07] bg-zinc-950 px-5 py-20"><div className="mx-auto max-w-5xl text-center"><p className="text-xs font-black uppercase tracking-[.25em] text-fuchsia-400">{text.premium}</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">{text.more}</h2><p className="mt-3 text-zinc-500">{text.payment}</p><div className="mt-10 grid gap-5 md:grid-cols-2">{plans.map(plan=><article key={plan.name} className="rounded-3xl border border-white/10 bg-gradient-to-br from-fuchsia-500/15 to-transparent p-7 text-left"><p className="font-black">PodLive {plan.name}</p><p className="mt-3 text-5xl font-black">₹{plan.price}<span className="text-sm text-zinc-500"> / {text.month}</span></p><ul className="mt-7 space-y-3">{plan.features[language].map(feature=><li key={feature} className="flex gap-3 text-sm text-zinc-300"><Check className="size-5 text-emerald-400"/>{feature}</li>)}</ul><Link href={`/subscribe?plan=${plan.name.toLowerCase()}`} className="mt-8 flex min-h-12 items-center justify-center rounded-xl bg-white font-black text-black">{text.choose} {plan.name}</Link></article>)}</div></div></section>
      <section id="faq" className="px-5 py-20"><div className="mx-auto max-w-3xl"><p className="text-xs font-black uppercase tracking-[.25em] text-indigo-400">{text.faqTitle}</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">{text.faqHeading}</h2><div className="mt-9 space-y-3">{faq[language].map(([question,answer],index)=><article key={question} className="rounded-2xl border border-white/[.08] bg-zinc-950"><button onClick={()=>setOpenFaq(openFaq===index?-1:index)} className="flex w-full items-center justify-between gap-4 p-5 text-left font-bold"><span>{question}</span><ChevronDown className={`size-5 transition ${openFaq===index?"rotate-180":""}`}/></button>{openFaq===index&&<p className="border-t border-white/[.07] p-5 text-sm leading-7 text-zinc-400">{answer}</p>}</article>)}</div></div></section>
    </main><footer className="border-t border-white/[.08] px-5 py-10"><div className="mx-auto flex max-w-7xl gap-5 text-xs text-zinc-500"><p>© 2026 PodLive</p><Link className="ml-auto" href="/terms">Terms</Link><Link href="/privacy">Privacy</Link></div></footer>
  </div>;
}
