"use client";

import { useState } from "react";
import Link from "next/link";
import { Check, ChevronDown, Languages, Mic, Play, Radio, ShieldCheck, Sparkles, Users } from "lucide-react";

const faqs = [
  ["What is PodLive? / PodLive क्या है?", "PodLive is an India-first video-sharing and live podcast platform where people can watch, learn, create and build communities. PodLive भारत का video sharing और live podcast platform है, जहाँ आप देख सकते हैं, सीख सकते हैं, content बना सकते हैं और अपनी community बढ़ा सकते हैं।"],
  ["How much does PodLive cost? / PodLive की कीमत क्या है?", "You can join and explore available public content for free. Plus costs ₹299/month and Max costs ₹599/month. आप free में account बनाकर उपलब्ध public content explore कर सकते हैं; Plus ₹299/महीना और Max ₹599/महीना है।"],
  ["Where can I watch? / मैं कहाँ देख सकता हूँ?", "Watch on supported phones, tablets and desktop browsers with a responsive player. आप supported mobile, tablet और desktop browser पर देख सकते हैं।"],
  ["What can I watch? / मैं क्या देख सकता हूँ?", "Explore technology, movies, comedy, education, finance, gaming, general knowledge, podcasts, blogs and live conversations—based on what creators publish. Technology, movies, comedy, education, finance, gaming, general knowledge, podcasts, blogs और live conversations देखें।"],
  ["Is PodLive good for kids? / क्या PodLive बच्चों के लिए अच्छा है?", "The general service is for users aged 13+ and minors need guardian permission. Content varies by creator, so parents should supervise viewing and use available safety controls. यह सामान्य सेवा 13+ users के लिए है; minors को guardian की अनुमति और supervision चाहिए।"],
] as const;

const plans = [
  { name: "Plus", price: 299, accent: "border-indigo-400/30 from-indigo-500/20", features: ["Ad-free videos", "Higher quality video", "Personalised video feed", "More live podcasts"] },
  { name: "Max", price: 599, accent: "border-fuchsia-400/30 from-fuchsia-500/20", features: ["Unlimited ad-free viewing", "Highest available quality", "Personalised video feed", "Unlimited podcast creation"] },
] as const;

export default function MarketingLanding() {
  const [openFaq, setOpenFaq] = useState(0);
  const [language, setLanguage] = useState(() => typeof window === "undefined" ? "hi" : localStorage.getItem("podliveLanguage") || "hi");
  const chooseLanguage = (value: string) => { setLanguage(value); localStorage.setItem("podliveLanguage", value); document.documentElement.lang = value; };
  return <div className="min-h-screen overflow-hidden bg-[#050505] text-white">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/75 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-6"><Link href="/" className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-red-500 to-fuchsia-600"><Mic className="size-5" /></span><span className="text-lg font-black">PodLive</span></Link><nav className="ml-auto hidden items-center gap-6 text-sm text-zinc-300 md:flex"><a href="#about">About / परिचय</a><a href="#plans">Plans / प्लान</a><a href="#faq">FAQ</a></nav><label className="relative ml-auto md:ml-4"><Languages className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-zinc-400"/><select aria-label="Language" value={language} onChange={(event) => chooseLanguage(event.target.value)} className="h-10 rounded-lg border border-white/15 bg-black pl-8 pr-2 text-xs outline-none"><option value="hi">हिन्दी</option><option value="en">English</option><option value="bn">বাংলা</option><option value="te">తెలుగు</option><option value="mr">मराठी</option><option value="ta">தமிழ்</option><option value="gu">ગુજરાતી</option><option value="kn">ಕನ್ನಡ</option><option value="ml">മലയാളം</option><option value="pa">ਪੰਜਾਬੀ</option><option value="or">ଓଡ଼ିଆ</option><option value="as">অসমীয়া</option></select></label><Link href="/login" className="hidden rounded-lg px-3 py-2 text-sm font-bold sm:block">Sign in</Link><Link href="/register" className="rounded-lg bg-red-600 px-3 py-2 text-xs font-black hover:bg-red-500 sm:text-sm">Sign up</Link></div></header>
    <main><section className="relative grid min-h-[92svh] place-items-center px-5 pb-16 pt-28 text-center"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_30%,rgba(220,38,38,.3),transparent_32%),radial-gradient(circle_at_20%_70%,rgba(124,58,237,.2),transparent_30%)]"/><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.06)_1px,transparent_1px)] [background-size:44px_44px]"/><div className="relative mx-auto max-w-5xl"><span className="inline-flex items-center gap-2 rounded-full border border-red-400/25 bg-red-500/10 px-4 py-2 text-xs font-bold text-red-200"><Radio className="size-4"/> India ka video sharing & live podcast मंच</span><h1 className="mt-7 text-4xl font-black leading-[1.05] tracking-tight sm:text-6xl lg:text-8xl">Unlimited views. <span className="bg-gradient-to-r from-red-400 via-fuchsia-400 to-indigo-400 bg-clip-text text-transparent">Har awaaz live.</span></h1><p className="mx-auto mt-6 max-w-3xl text-base leading-7 text-zinc-300 sm:text-xl">Technology, movies, comedy, education, finance, gaming, general knowledge, podcasts, blogs aur live fun—sab ek jagah, PodLive par.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-xl bg-red-600 px-7 font-black hover:bg-red-500"><Play className="size-5 fill-current"/> Abhi shuru karein</Link><Link href="/login" className="inline-flex min-h-13 items-center justify-center rounded-xl border border-white/20 bg-white/10 px-7 font-bold backdrop-blur hover:bg-white/15">Sign in / लॉग इन</Link></div><p className="mt-4 text-xs text-zinc-500">Join free. Premium plans are optional. / Free account बनाएं, premium optional है।</p></div></section>
      <section id="about" className="border-y border-white/[.07] bg-zinc-950 px-5 py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.25em] text-red-400">What is PodLive?</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">India ki stories, skills aur conversations ka digital stage.</h2><p className="mt-6 leading-8 text-zinc-400">PodLive creators और viewers को videos, live podcasts, learning content और communities के through जोड़ता है। Watch, create, go live, interact और अपने channel को grow करें—phone, tablet या browser से।</p><p className="mt-5 text-sm leading-7 text-zinc-500">Founded by <strong className="text-zinc-300">Amitesh Kumar Yadav</strong>, with co-founders <strong className="text-zinc-300">Adarsh Kumar</strong> and <strong className="text-zinc-300">Aman Nawhar</strong>.</p></div><div className="grid grid-cols-2 gap-3">{[[Sparkles,"Unlimited discovery","Naya content, naye creators"],[Radio,"Live fun","Real-time podcasts"],[Users,"Creator communities","Like, comment, follow"],[ShieldCheck,"Creator control","Analytics & monetization"]].map(([Icon,title,desc])=><div key={String(title)} className="rounded-2xl border border-white/[.08] bg-white/[.03] p-5"><Icon className="size-6 text-red-400"/><h3 className="mt-5 font-bold">{String(title)}</h3><p className="mt-1 text-xs text-zinc-500">{String(desc)}</p></div>)}</div></div></section>
      <section id="plans" className="px-5 py-20"><div className="mx-auto max-w-5xl text-center"><p className="text-xs font-black uppercase tracking-[.25em] text-fuchsia-400">Premium plans</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">Watch more. Create more.</h2><p className="mt-3 text-zinc-500">Monthly plans. Payment activation happens only after secure verification.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{plans.map((plan)=><article key={plan.name} className={`rounded-3xl border bg-gradient-to-br ${plan.accent} to-transparent p-7 text-left`}><p className="font-black text-zinc-300">PodLive {plan.name}</p><p className="mt-3 text-5xl font-black">₹{plan.price}<span className="text-sm font-medium text-zinc-500"> / month</span></p><ul className="mt-7 space-y-3">{plan.features.map(feature=><li key={feature} className="flex gap-3 text-sm text-zinc-300"><Check className="size-5 shrink-0 text-emerald-400"/>{feature}</li>)}</ul><Link href={`/subscribe?plan=${plan.name.toLowerCase()}`} className="mt-8 flex min-h-12 items-center justify-center rounded-xl bg-white font-black text-black hover:bg-zinc-200">Choose {plan.name}</Link></article>)}</div></div></section>
      <section id="faq" className="border-t border-white/[.07] bg-zinc-950 px-5 py-20"><div className="mx-auto max-w-3xl"><p className="text-xs font-black uppercase tracking-[.25em] text-indigo-400">Frequently asked questions</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">Sawal? Jawab yahan hai.</h2><div className="mt-9 space-y-3">{faqs.map(([question,answer],index)=><article key={question} className="overflow-hidden rounded-2xl border border-white/[.08] bg-black"><button onClick={()=>setOpenFaq(openFaq===index?-1:index)} className="flex w-full items-center justify-between gap-4 p-5 text-left font-bold"><span>{question}</span><ChevronDown className={`size-5 shrink-0 transition ${openFaq===index?"rotate-180":""}`}/></button>{openFaq===index&&<p className="border-t border-white/[.07] px-5 py-5 text-sm leading-7 text-zinc-400">{answer}</p>}</article>)}</div></div></section>
    </main><footer className="border-t border-white/[.08] px-5 py-10"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-xs text-zinc-500 sm:flex-row sm:items-center"><p>© 2026 PodLive. Har awaaz ko ek stage.</p><div className="flex gap-5 sm:ml-auto"><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/login">Sign in</Link></div></div></footer>
  </div>;
}
